@Library('cicd-library') _

import org.jenkinsci.plugins.gwt.GenericTrigger

def CONFIG = null
def BUILD_QUEUE = []


pipeline {

    agent any

    triggers {
        GenericTrigger(token: 'orchestrator-trigger')        
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
        timestamps()
    }

    environment {

        CONTROL_REPO =
        "git@github.com:profit-apps-inc/jenkins-cicd-env-control.git"

        CONTROL_BRANCH =
        "cicd"

        BUILD_STATE_DIR =
        "/u01/jenkins/jenkins/build-state"

        DEPLOY_STATE_DIR =
        "/u01/jenkins/jenkins/deploy-state"

        FILEGEN_STATE_DIR =
        "/u01/jenkins/jenkins/filegen-state"
    }

    stages {

        stage('Load Mapping') {

            steps {

                script {

                    echo """
                    =====================================
                    Loading Configuration
                    =====================================
                    """

                    CONFIG = loadMappings()
                    
                    env.DOCKER_REPO =
                        CONFIG.docker.repo ?: ''

                    env.DOCKER_BRANCH =
                        CONFIG.docker.branch ?: ''

                    env.DOCKER_DIR =
                        CONFIG.docker.context_dir ?: ''

                    echo """
                    =====================================
                    Configuration Loaded
                    =====================================

                    MAPPINGS     : ${CONFIG.mappings.size()}
                    BUILDERS     : ${CONFIG.builders.size()}
                    ENVIRONMENTS : ${CONFIG.environments.keySet().join(', ')}

                    DOCKER REPO  : ${env.DOCKER_REPO}
                    """
                }
            }
        }

        stage('Detect Changes') {

            steps {

                script {

                    BUILD_QUEUE = []

                    def seen = []

                    CONFIG.mappings.each { key, value ->

                        def app     = value.app.toString()
                        def repo    = value.repo.toString()
                        def branch  = value.branch.toString()
                        def envName = value.env.toString()
                        def envCfg = CONFIG.environments[envName]
                        echo """
                        =====================================
                        Environment Configuration
                        =====================================

                        ENV           : ${envName}
                        REGISTRY      : ${envCfg.docker_build?.container_registry}
                        IMAGE REPO    : ${envCfg.docker_build?.image_repo}
                        DEPLOY TYPE   : ${envCfg.deployment?.type}
                        """
                        if (!envCfg) {

                            error """
                            Environment configuration missing

                            ENV : ${envName}
                            """
                        }
                        def actions =
                            (value.actions ?: [])
                            .collect { it.toString().trim() }

                        def id = "${app}:${envName}"

                        if (seen.contains(id)) {

                            error """
                            ❌ Duplicate Mapping

                            ${id}
                            """
                        }

                        seen << id

                        echo """
                        =====================================
                        Checking Repository
                        =====================================

                        APP      : ${app}
                        REPO     : ${repo}
                        BRANCH   : ${branch}
                        ENV      : ${envName}
                        ACTIONS  : ${actions.join(',')}
                        """

                        def commit = sh(
                            script: """
                            git ls-remote ${repo} refs/heads/${branch} \
                            | cut -f1
                            """,
                            returnStdout: true
                        ).trim()

                        if (!commit) {

                            echo """
                            ⚠️ Unable to fetch commit

                            APP : ${app}
                            """

                            return
                        }

                        def buildStateFile =
                            "${env.BUILD_STATE_DIR}/${app}/${envName}.commit"

                        def fileStateFile =
                            "${env.FILEGEN_STATE_DIR}/${app}/${envName}.commit"

                        def buildState = sh(
                            script: """
                            [ -f ${buildStateFile} ] &&
                            cat ${buildStateFile} ||
                            echo none
                            """,
                            returnStdout: true
                        ).trim()

                        def fileState = sh(
                            script: """
                            [ -f ${fileStateFile} ] &&
                            cat ${fileStateFile} ||
                            echo none
                            """,
                            returnStdout: true
                        ).trim()

                        def deployStateFile =
                            "${env.DEPLOY_STATE_DIR}/${app}/${envName}.commit"

                        def deployState = sh(
                            script: """
                            [ -f ${deployStateFile} ] &&
                            cat ${deployStateFile} ||
                            echo none
                            """,
                            returnStdout: true
                        ).trim()

                        echo """
                        =====================================
                        Commit Status
                        =====================================

                        LATEST COMMIT : ${commit}
                        BUILD STATE   : ${buildState}
                        FILE STATE    : ${fileState}
                        DEPLOY STATE  : ${deployState}

                        BUILD MATCH   : ${commit == buildState}
                        FILE MATCH    : ${commit == fileState}
                        """

                        def needBuild =
                            actions.contains('build') &&
                            commit != buildState

                        def needFC =
                            actions.contains('FC') &&
                            commit != fileState

                        def needDeploy =
                            actions.contains('deploy') &&
                            commit != deployState

                        if (!needBuild && !needFC && !needDeploy) {

                            echo """
                            No changes detected

                            APP : ${app}
                            """

                            return
                        }

                        def webhooks = []

                        webhooks.addAll(
                            CONFIG.notifications.default ?: []
                        )

                        webhooks.addAll(
                            CONFIG.notifications.environments[envName] ?: []
                        )

                        BUILD_QUEUE << [

                            app       : app,
                            env       : envName,
                            branch    : branch,
                            commit    : commit,
                            needBuild : needBuild,
                            needFC    : needFC,
                            needDeploy : needDeploy,
                            repo       : value.repo,
                            registry   : envCfg.docker_build?.container_registry ?: '',
                            image_repo : envCfg.docker_build?.image_repo ?: '',
                            war_name   : envCfg.docker_build?.war_name ?: '',
                            war_context: envCfg.docker_build?.war_context?: '',
                            fcDestination : envCfg.cdn?.fc_destination ?: '',
                            gcpBucket : envCfg.cdn?.gcp_bucket ?: '',
                            cdnKeep : envCfg.cdn?.keep_version ?: '',
                            gcpUrl : envCfg.cdn?.gcp_url ?: '',
                            awsBucket : envCfg.cdn?.aws_bucket ?: '',
                            awsUrl : envCfg.cdn?.aws_url ?: '',                            
                            sshHost : envCfg.shared?.ssh_host ?: '',
                            esUrl : envCfg.switch?.elasticsearch?.url ?: '',
                            esIndex : envCfg.switch?.elasticsearch?.index ?: '',
                            gcpDocId : envCfg.switch?.elasticsearch?.gcp?.doc_id ?: '',
                            awsDocId : envCfg.switch?.elasticsearch?.aws?.doc_id ?: '',
                            cacheClearEnabled : envCfg.cache_clear?.enabled ?: false,
                            cacheClearTargets: envCfg.cache_clear?.targets ?: [:],
                            cacheClearApiKey: envCfg.cache_clear?.api_key_credential ?: '',
                            cacheClearAccessKey: envCfg.cache_clear?.access_key_credential ?: '',
                            deployType : envCfg.deployment?.type ?: '',
                            deployStrategy : envCfg.deployment?.strategy ?: '',
                            deployTargets : envCfg.deployment?.targets ?: [:],
                            approvalRequired : envCfg.promotion?.approval_required ?: false,
                            notificationWebhooks: webhooks.unique()

                        ]                        
                    }                    

                    if (BUILD_QUEUE.isEmpty()) {

                        env.HAS_CHANGES = "false"

                        currentBuild.description =
                        "No changes"

                        echo """
                        =====================================
                        No Changes Across Repositories
                        =====================================
                        """

                        return
                    }

                    env.HAS_CHANGES = "true"

                    echo """
                    =====================================
                    Build Queue
                    =====================================

                    ${BUILD_QUEUE.collect {
                        """
                        APP        : ${it.app}
                        ENV        : ${it.env}
                        BRANCH     : ${it.branch}
                        NEED_BUILD : ${it.needBuild}                        
                        DEPLOY     : ${it.needDeploy}
                        NEED_FC    : ${it.needFC}
                        """
                    }.join('\n')}
                    """
                }
            }
        }

        stage('Start Build VM') {

            when {

                expression {
                    env.HAS_CHANGES == "true"
                }
            }

            steps {

                script {
                    

                    def buildBuilder =
                        selectBuilder(
                            'build',
                            CONFIG
                        )

                    def filesBuilder =
                        selectBuilder(
                            'files',
                            CONFIG
                        )

                    def buildZone =
                        CONFIG.builders[buildBuilder].zone

                    def filesZone =
                        CONFIG.builders[filesBuilder].zone

                    def needBuildVM = BUILD_QUEUE.any { item ->

                        item.needBuild
                    }

                    def needFilesVM = BUILD_QUEUE.any { item ->

                        item.needFC
                    }

                    echo """
                    =====================================
                    VM Requirements
                    =====================================

                    BUILD VM : ${needBuildVM}
                    FILES VM : ${needFilesVM}
                    """

                    def vmStarts = [:]

                    if (needFilesVM) {

                        vmStarts[filesBuilder] = {

                            builderManager(
                                action : "acquire",
                                builder: filesBuilder,
                                zone   : filesZone
                            )
                        }
                    }

                    if (needBuildVM) {

                        vmStarts[buildBuilder] = {

                            builderManager(
                                action : "acquire",
                                builder: buildBuilder,
                                zone   : buildZone
                            )
                        }
                    }

                    if (!vmStarts.isEmpty()) {

                        parallel vmStarts
                    }
                }
            }
        }

        stage('Run Pipelines') {
            when {
                expression {
                    env.HAS_CHANGES == "true"
                }
            }

            steps {

                script {

                    def queueJobs = [:]

                    BUILD_QUEUE.each { item ->

                        queueJobs["${item.app}-${item.env}"] = {

                            echo """
                            =====================================
                            PROCESSING
                            =====================================

                            APP        : ${item.app}
                            ENV        : ${item.env}
                            COMMIT     : ${item.commit}
                            NEED_BUILD : ${item.needBuild}
                            NEED_FC    : ${item.needFC}
                            NEED_DEPLOY: ${item.needDeploy}
                            """

                            notify(
                                app      : item.app,
                                env      : item.env,
                                msg      : "PIPELINE REQUEST (${item.branch})",
                                commit   : item.commit,
                                webhooks : item.notificationWebhooks
                            )

                            def buildPipelineResult = null
                            def filesPipelineResult = null

                            /*
                            |--------------------------------------------------------------------------
                            | BUILD
                            |--------------------------------------------------------------------------
                            */
                            def appJobs = [:]

                            /*
                            |--------------------------------------------------------------------------
                            | BUILD (+ DEPLOY)
                            |--------------------------------------------------------------------------
                            */

                            if (item.needBuild) {

                                appJobs["Build"] = {

                                    buildPipelineResult = build(
                                        job: 'Build-Pipeline',
                                        wait: true,
                                        propagate: true,
                                        parameters: [
                                            string(name:'APP_NAME', value:item.app),
                                            string(name:'TARGET_ENV', value:item.env),
                                            string(name:'COMMIT_FULL', value:item.commit),
                                            string(name:'REPO_URL', value:item.repo),
                                            string(name:'BRANCH_NAME', value:item.branch),
                                            string(name:'REGISTRY', value:item.registry),
                                            string(name:'IMAGE_REPO', value:item.image_repo),
                                            string(name:'DOCKER_REPO', value:env.DOCKER_REPO),
                                            string(name:'DOCKER_BRANCH', value:env.DOCKER_BRANCH),
                                            string(name:'DOCKER_DIR', value:env.DOCKER_DIR),
                                            string(name:'WAR_NAME', value:item.war_name),
                                            string(name:'WAR_CONTEXT', value:item.war_context),
                                            text(
                                                name:'NOTIFICATION_WEBHOOKS',
                                                value:writeJSON(
                                                    returnText:true,
                                                    json:item.notificationWebhooks
                                                )
                                            )
                                        ]
                                    )

                                    sh """
                                    mkdir -p ${env.BUILD_STATE_DIR}/${item.app}

                                    echo ${item.commit} > \
                                    ${env.BUILD_STATE_DIR}/${item.app}/${item.env}.commit
                                    """

                                    def metadata =
                                        buildPipelineResult?.description ?
                                        readJSON(text: buildPipelineResult.description) :
                                        [:]

                                    def history = [
                                        app          : item.app,
                                        branch       : item.branch,
                                        commit       : item.commit,
                                        short_commit : item.commit.take(7),
                                        md5          : metadata.md5 ?: "",
                                        version      : metadata.version ?: "",
                                        image        : metadata.image ?: "",
                                        build        : buildPipelineResult.number,
                                        env          : item.env,
                                        type         : "BUILD"
                                    ]

                                    buildHistory(history)
                                    notifyHistory(history)

                                    /*
                                    -------------------------------------------------------------
                                    DEPLOY AFTER BUILD
                                    -------------------------------------------------------------
                                    */

                                    if (item.needDeploy) {

                                        build(
                                            job: 'Deploy-Pipeline',
                                            wait: true,
                                            propagate: true,
                                            parameters: [
                                                string(name:'APP_NAME', value:item.app),
                                                string(name:'TARGET_ENV', value:item.env),
                                                string(name:'VERSION', value:metadata.version ?: ""),
                                                string(name:'COMMIT_FULL', value:item.commit),
                                                text(
                                                    name:'NOTIFICATION_WEBHOOKS',
                                                    value:writeJSON(
                                                        returnText:true,
                                                        json:item.notificationWebhooks
                                                    )
                                                )
                                            ]
                                        )
                                    }
                                }

                            } else if (item.needDeploy) {

                                /*
                                |--------------------------------------------------------------------------
                                | DEPLOY ONLY
                                |--------------------------------------------------------------------------
                                */

                                appJobs["Deploy"] = {

                                    build(
                                        job: 'Deploy-Pipeline',
                                        wait: true,
                                        propagate: true,
                                        parameters: [
                                            string(name:'APP_NAME', value:item.app),
                                            string(name:'TARGET_ENV', value:item.env),
                                            string(name:'VERSION', value:item.version ?: ""),
                                            string(name:'COMMIT_FULL', value:item.commit),
                                            text(
                                                name:'NOTIFICATION_WEBHOOKS',
                                                value:writeJSON(
                                                    returnText:true,
                                                    json:item.notificationWebhooks
                                                )
                                            )
                                        ]
                                    )
                                }
                            }

                            /*
                            |--------------------------------------------------------------------------
                            | FILES
                            |--------------------------------------------------------------------------
                            */

                            if (item.needFC) {

                                appJobs["Files"] = {

                                    filesPipelineResult = build(
                                        job: 'Files-Pipeline',
                                        wait: true,
                                        propagate: true,
                                        parameters: [

                                            string(name:'APP_NAME', value:item.app),
                                            string(name:'TARGET_ENV', value:item.env),
                                            string(name:'COMMIT_FULL', value:item.commit),
                                            string(name:'REPO_URL', value:item.repo),
                                            string(name:'BRANCH_NAME', value:item.branch),
                                            string(name:'FC_DESTINATION', value:item.fcDestination),
                                            string(name:'CDN_KEEP', value:"${item.cdnKeep}"),
                                            string(name:'GCP_BUCKET', value:item.gcpBucket),
                                            string(name:'GCP_URL', value:item.gcpUrl),
                                            string(name:'AWS_S3_BUCKET', value:item.awsBucket),
                                            string(name:'AWS_S3_URL', value:item.awsUrl),
                                            string(name:'SSH_HOST', value:item.sshHost),
                                            string(name:'ES_URL', value:"${item.esUrl}"),
                                            string(name:'ES_INDEX', value:"${item.esIndex}"),
                                            string(name:'GCP_DOC_ID', value:"${item.gcpDocId}"),
                                            string(name:'AWS_DOC_ID', value:"${item.awsDocId}"),
                                            string(name:'CACHE_ENABLED', value:"${item.cacheClearEnabled}"),
                                            text(name:'CACHE_TARGETS', value:writeJSON(returnText:true, json:item.cacheClearTargets)),
                                            string(name:'CACHE_API', value:item.cacheClearApiKey),
                                            string(name:'CACHE_ACCESS', value:item.cacheClearAccessKey),
                                            text(name:'NOTIFICATION_WEBHOOKS', value:writeJSON(returnText:true, json:item.notificationWebhooks))
                                        ]
                                    )

                                    sh """
                                    mkdir -p ${env.FILEGEN_STATE_DIR}/${item.app}

                                    echo ${item.commit} > \
                                    ${env.FILEGEN_STATE_DIR}/${item.app}/${item.env}.commit
                                    """

                                    def fileVersion =
                                        filesPipelineResult.description ?: ""

                                    def history = [
                                        app          : item.app,
                                        env          : item.env,
                                        branch       : item.branch,
                                        commit       : item.commit,
                                        short_commit : item.commit.take(7),
                                        version      : fileVersion,
                                        gcp_url      : item.gcpUrl ? "${item.gcpUrl}/${fileVersion}" : "",
                                        aws_url      : item.awsUrl ? "${item.awsUrl}/${fileVersion}" : "",
                                        build        : filesPipelineResult.number,
                                        type         : "FILES"
                                    ]

                                    filesHistory(history)
                                    notifyHistory(history)
                                }
                            }

                            if (!appJobs.isEmpty()) {
                                parallel appJobs
                            }     
                        }
                    }
                    if (!queueJobs.isEmpty()) {

                        parallel queueJobs
                    }
                }
            }                   
        }
    }    
    post {

        always {

            script {
                if (env.HAS_CHANGES == "true") {

                    def needBuildVM = BUILD_QUEUE.any { item ->

                        item.needBuild
                    }

                    def needFilesVM = BUILD_QUEUE.any { item ->

                        item.needFC
                    }

                    def buildBuilder =
                        selectBuilder(
                            'build',
                            CONFIG
                        )

                    def filesBuilder =
                        selectBuilder(
                            'files',
                            CONFIG
                        )

                    def buildZone =
                        CONFIG.builders[buildBuilder].zone

                    def filesZone =
                        CONFIG.builders[filesBuilder].zone
                    
                    
                    def vmStops = [:]

                    if (needFilesVM) {

                        vmStops[filesBuilder] = {

                            echo """
                            =====================================
                            Stopping Builder-01 VM
                            =====================================

                            VM   : ${filesBuilder}
                            ZONE : ${filesZone}
                            """

                            builderManager(
                                action : "release",
                                builder: filesBuilder,
                                zone   : filesZone
                            )

                            sleep(time:10, unit:'MINUTES')
                            
                            builderManager(
                                action : "idleShutdown",
                                builder: filesBuilder,
                                zone: filesZone
                            )
                        }
                    }

                    if (needBuildVM) {

                        vmStops[buildBuilder] = {

                            echo """
                            =====================================
                            Stopping Builder-02 VM
                            =====================================

                            VM   : ${buildBuilder}
                            ZONE : ${buildZone}
                            """

                            builderManager(
                                action : "release",
                                builder: buildBuilder,
                                zone   : buildZone
                            )

                            sleep(time:10, unit:'MINUTES')

                            builderManager(
                                action : "idleShutdown",
                                builder: buildBuilder,
                                zone: buildZone
                            )
                        }
                    }

                    if (!vmStops.isEmpty()) {

                        parallel vmStops
                    }

                    echo """
                    =====================================
                    ✅ Builder VM(s) Stopped
                    =====================================
                    """
                }            
            }
        }
            

        failure {

            script {

                notify(                    
                    app: "orchestrator",                    
                    msg: "FAILED ❌",
                    webhooks: CONFIG.notifications.default
                )
            }
        }

        success {

            echo """
            =====================================
            ✅ ORCHESTRATOR SUCCESS
            =====================================
            """
        }
    }
}