@Library('cicd-library') _

import java.util.UUID

pipeline {

    agent any

    triggers {

        GenericTrigger(

            token: 'request-trigger',

            genericVariables: [

                [key:'ACTION', value:'$.action'],
                [key:'MERGED', value:'$.pull_request.merged'],
                [key:'LABEL', value:'$.pull_request.labels[0].name'],
                [key:'PR', value:'$.pull_request.number'],
                [key:'REPO', value:'$.repository.name'],
                [key:'USER', value:'$.sender.login']
            ],

            regexpFilterText: '$ACTION',

            regexpFilterExpression: '^closed$',

            printContributedVariables: true,

            printPostContent: true
        )
    }

    options {

        disableConcurrentBuilds()

        buildDiscarder(
            logRotator(numToKeepStr: '20')
        )

        timestamps()
    }

    stages {

        stage('Process Deployment Request') {

            steps {

                script {

                    /*
                    ----------------------------------------------------------
                    Read GitHub Webhook
                    ----------------------------------------------------------
                    */

                    echo "POST_CONTENT = ${env.POST_CONTENT}"
                    echo "LABEL        = ${env.LABEL}"

                    if (env.ACTION != "closed") {

                        env.PROCESS_REQUEST = "false"

                        currentBuild.result = "NOT_BUILT"

                        echo "Ignoring event: ${env.ACTION}"

                        return
                    }

                    if (env.MERGED != "true") {

                        env.PROCESS_REQUEST = "false"

                        currentBuild.result = "NOT_BUILT"

                        echo "PR closed without merge."

                        return
                    }


                    /*
                    ----------------------------------------------------------
                    Read Deployment Labels
                    ----------------------------------------------------------
                    */

                    def CONFIG = loadMappings()                    

                    def deployment =
                         loadRequestLabel([env.LABEL], CONFIG)

                    if (!deployment) {

                        env.PROCESS_REQUEST = "false"

                        currentBuild.result = "NOT_BUILT"

                        echo "No deployment request label."

                        return
                    }
                    
                    /*
                    ----------------------------------------------------------
                    Create Deployment Request
                    ----------------------------------------------------------
                    */

                    def request = [

                        id : UUID.randomUUID().toString(),

                        app : env.REPO,

                        pr : env.PR.toInteger(),

                        requestLabel : deployment.label,

                        env : deployment.env,

                        actions : deployment.actions,

                        status : "pending",

                        requested_by : env.USER,

                        requested_at : new Date().format(
                            "yyyy-MM-dd'T'HH:mm:ss'Z'",
                            TimeZone.getTimeZone("UTC")
                        )
                    ]

                    updateRequests(

                        action : "add",

                        request : request
                    )

                    env.PROCESS_REQUEST = "true"

                    /*
                    ----------------------------------------------------------
                    Summary
                    ----------------------------------------------------------
                    */

                    echo """

                    =====================================
                    DEPLOYMENT REQUEST CREATED
                    =====================================

                    APP           : ${request.app}
                    PR            : #${request.pr}
                    REQUEST LABEL : ${request.requestLabel}
                    ENV           : ${request.env}
                    ACTIONS       : ${request.actions.join(',')}
                    REQUESTED BY  : ${request.requested_by}
                    STATUS        : ${request.status}

                    """
                }
            }
        }

        stage('Trigger Orchestrator') {

            when {

                expression {

                    return env.PROCESS_REQUEST == "true"
                }
            }

            steps {

                build(

                    job: 'Orchestrator-Pipeline',

                    wait: false
                )
            }
        }
    }
}