@Library('cicd-library') _
def hasAction(String action) {

    if (!env.ACTIONS) {

        return false
    }

    def actions =
    env.ACTIONS.split(',')

    for (String item : actions) {

        if (item.trim() == action) {

            return true
        }
    }

    return false
}
pipeline {

    agent {
        label 'docker-builder'
    }

    parameters {

        string(name: 'APP_NAME')
        string(name: 'TARGET_ENV')
        string(name: 'COMMIT_FULL')
    }

    options {

        disableConcurrentBuilds(
            abortPrevious: true
        )

        buildDiscarder(
            logRotator(numToKeepStr: '10')
        )

        timestamps()
    }

    environment {
        STATE_DIR =
        "/u01/jenkins/jenkins/build-state"

        ARTIFACT_DIR =
        "/u01/jenkins/jenkins/artifacts/${params.APP_NAME}"
    }

    stages {        

        stage('Init') {

            steps {

                deleteDir()

                echo """
                =====================================
                Workspace Cleaned
                =====================================
                """
            }
        }

        stage('Load Config') {

            steps {

                script {

                    echo """
                    =====================================
                    Loading Mapping
                    =====================================

                    APP : ${params.APP_NAME}
                    ENV : ${params.TARGET_ENV}     
                    """

                    def config =

                    loadConfig(
                        params.APP_NAME,
                        params.TARGET_ENV
                    )

                    def mapping =
                    config.mapping

                    env.ACTIONS =
                    (mapping.actions ?: [])
                    .collect { it.toString().trim() }
                    .join(',')

                    env.REPO_URL =
                    mapping.repo.toString()

                    env.BRANCH_NAME =
                    mapping.branch.toString()

                    env.REGISTRY =
                    mapping.registry.toString()

                    env.IMAGE_REPO =
                    mapping.image_repo.toString()

                    env.DOCKER_REPO =
                    config.docker.repo.toString()

                    env.DOCKER_BRANCH =
                    config.docker.branch.toString()

                    env.NAMESPACE =
                    mapping.namespace.toString()

                    env.WORKLOAD =
                    mapping.workload.toString()

                    env.IMAGE =
                    "${mapping.registry}/${mapping.image_repo}"

                    env.CDN_BUCKET =
                    mapping.cdn?.bucket ?: ""

                    env.CDN_PATH =
                    mapping.cdn?.path ?: ""

                    env.CDN_KEEP =
                    mapping.cdn?.keep_versions?.toString() ?: "100"

                    echo """
                    =====================================
                    Configuration Loaded
                    ===================================== 
                    REPO        : ${env.REPO_URL}
                    BRANCH      : ${env.BRANCH_NAME}
                    IMAGE       : ${env.IMAGE}
                    NAMESPACE   : ${env.NAMESPACE}
                    WORKLOAD    : ${env.WORKLOAD}
                    """  

                    
                }
            }
        }

        stage('Checkout App Repo') {

            steps {

                echo """
                =====================================
                Checkout App Repository
                =====================================

                REPO   : ${env.REPO_URL}
                BRANCH : ${env.BRANCH_NAME}
                """

                git(
                    url: env.REPO_URL,
                    branch: env.BRANCH_NAME,
                    credentialsId: 'github-token'
                )
            }
        }

        stage('Generate Files') {

            when {

                expression {

                    hasAction('generate_files')
                }
            }

            steps {

                script {

                    stageExec(

                        params.APP_NAME,
                        params.TARGET_ENV,
                        "FILE GENERATION"

                    ) {

                        generateFiles(

                            app: params.APP_NAME,

                            env: params.TARGET_ENV,

                            workspace: env.WORKSPACE
                        )
                    }
                }
            }
        }

        stage('File Versioning') {

            when {

                expression {

                    hasAction('cdn_copy')
                }
            }

            steps {

                script {

                    env.FILE_VERSION =

                    incrementFileVersion(

                        bucket:
                        env.CDN_BUCKET
                    )

                    echo """
                    =====================================
                    FILE VERSION GENERATED
                    =====================================

                    VERSION : ${env.FILE_VERSION}
                    """
                }
            }
        }

        stage('Copy Files To GCP CDN') {

            when {

                expression {

                    hasAction('cdn_copy')
                }
            }

            steps {

                script {

                    stageExec(

                        params.APP_NAME,
                        params.TARGET_ENV,
                        "GCP CDN COPY"

                    ) {

                        copyToGcpCdn(

                            source:
                            "build-output/files",

                            bucket:
                            "${env.CDN_BUCKET}/${env.CDN_PATH}",

                            version:
                            env.FILE_VERSION
                        )
                    }
                }
            }
        }

        stage('Cleanup Old CDN Versions') {

            when {

                expression {

                    hasAction('cdn_copy')
                }
            }

            steps {

                script {

                    stageExec(

                        params.APP_NAME,
                        params.TARGET_ENV,
                        "CDN CLEANUP"

                    ) {

                        cleanupOldCdnVersions(

                            bucket:
                            "${env.CDN_BUCKET}/${env.CDN_PATH}",

                            keep:
                            env.CDN_KEEP.toInteger()
                        )
                    }
                }
            }
        }

        stage('Checkout Docker Repo') {

            when {

                expression {

                    hasAction('build')
                }
            }

            steps {

                echo """
                =====================================
                Checkout Docker Repository
                =====================================

                REPO   : ${env.DOCKER_REPO}
                BRANCH : ${env.DOCKER_BRANCH}
                """

                dir('app-tomcat') {

                    deleteDir()

                    git(
                        url: env.DOCKER_REPO,
                        branch: env.DOCKER_BRANCH,
                        credentialsId: 'github-token'
                    )
                }               
            }
        }

        stage('Versioning') {

            when {

                expression {

                    hasAction('build')
                }
            }

            steps {

                script {

                    env.COMMIT_SHORT =
                    params.COMMIT_FULL.take(7)

                    env.VERSION =
                    generateVersion(
                        env.IMAGE,
                        env.COMMIT_SHORT
                    )

                    env.COMMIT_FULL =
                    params.COMMIT_FULL

                    currentBuild.description =
                    env.VERSION

                    currentBuild.displayName =
                    "${params.APP_NAME} ${env.VERSION}"

                    echo """
                    =====================================
                    Build Metadata
                    =====================================

                    VERSION : ${env.VERSION}
                    COMMIT  : ${params.COMMIT_FULL}
                    IMAGE   : ${env.IMAGE}
                    """
                }
            }
        }

        stage('Build WAR') {

            when {
                expression {
                    hasAction('build')                         
                }
            }

            steps {

                script {                    
                    
                    def warCache =
                    "${env.ARTIFACT_DIR}/${env.COMMIT_SHORT}.war"

                    def warExists = sh(

                        script: """
                        [ -f "${warCache}" ] &&
                        echo yes ||
                        echo no
                        """,

                        returnStdout: true

                    ).trim()

                    if (warExists == "yes") {

                        echo """
                        =====================================
                        Reusing Cached WAR
                        =====================================

                        FILE : ${warCache}
                        """

                        sh """
                        mkdir -p build-output

                        cp ${warCache} \
                        build-output/app.war
                        """

                    } else {

                        stageExec(
                            params.APP_NAME,
                            params.TARGET_ENV,
                            "WAR BUILD"
                        ) {

                            buildWar(
                                profile: params.TARGET_ENV
                                )
                        }    

                        sh """
                        mkdir -p build-output

                        mkdir -p ${env.ARTIFACT_DIR}

                        WAR_FILE=\$(find app-web/target \
                        -name "*.war" \
                        | head -1)

                        cp "\$WAR_FILE" \
                        build-output/app.war

                        cp build-output/app.war \
                        ${warCache}
                        """

                        echo """
                        =====================================
                        WAR Cached
                        =====================================

                        FILE : ${warCache}
                        """
                    }

                    env.WAR_MD5 = sh(

                        script:
                        "md5sum build-output/app.war | awk '{print \$1}'",

                        returnStdout: true

                    ).trim()

                    notify(
                        app: params.APP_NAME,
                        env: params.TARGET_ENV,
                        msg: "WAR READY"
                    )
                }
            }
        }

        stage('Cleanup Old WARs') {

            when {

                expression {

                    hasAction('build')
                }
            }

            steps {

                sh """
                cd ${env.ARTIFACT_DIR}

                ls -tp *.war \
                | tail -n +4 \
                | xargs -r rm -f
                """

                echo """
                =====================================
                WAR Cleanup Complete
                =====================================

                Keeping latest 3 WARs
                """
            }
        }

        stage('Inject WAR Into Docker Context') {

            when {

                expression {

                    hasAction('build')
                }
            }

            steps {

                sh """
                mkdir -p \
                app-tomcat/app/live

                cp build-output/app.war \
                app-tomcat/app/live/app.war

                echo ""
                echo "Docker WAR Verification"
                echo "-------------------------------------"

                ls -lh app-tomcat/app/live
                """
            }
        }

        stage('Docker Build + Push') {

            when {
                expression {
                    hasAction('build')                            
                }
            }

            steps {

                script {

                    def imageCache =
                    "${env.IMAGE}:${env.VERSION}"

                    def imageExists = sh(

                        script: """
                        gcloud artifacts docker tags list \
                        ${env.IMAGE} \
                        --format='value(TAG)' 2>/dev/null \
                        | grep '^${env.VERSION}\$' > /dev/null &&
                        echo yes ||
                        echo no
                        """,

                        returnStdout: true

                    ).trim()

                    if (imageExists == "yes") {

                        echo """
                        =====================================
                        Docker Image Reused
                        =====================================

                        IMAGE : ${imageCache}

                        =====================================
                        """

                    } else {

                        stageExec(
                            params.APP_NAME,
                            params.TARGET_ENV,
                            "DOCKER BUILD"
                        ) {

                            writeFile(
                                file: 'docker.sh',
                                text: libraryResource(
                                    'scripts/docker.sh'
                                )
                            )

                            sh 'chmod +x docker.sh'

                            sh """
                            ./docker.sh \
                            ${env.IMAGE} \
                            ${env.VERSION}
                            """
                        }
                    }
                }
            }
        }        

        stage('Update State') {

            when {

                expression {

                    hasAction('build')
                }
            }

            steps {

                sh """
                mkdir -p \
                ${env.STATE_DIR}/${params.APP_NAME}

                echo ${params.COMMIT_FULL} > \
                ${env.STATE_DIR}/${params.APP_NAME}/${params.TARGET_ENV}.commit
                """

                echo """
                =====================================
                State Updated
                =====================================
                """
            }
        }

        stage('History') {

            when {

                expression {

                    hasAction('build')
                }
            }

            steps {

                script {

                    buildHistory([

                        app: params.APP_NAME,

                        branch: env.BRANCH_NAME,

                        commit: params.COMMIT_FULL,

                        short_commit: env.COMMIT_SHORT,

                        version: env.VERSION,

                        image:
                        "${env.IMAGE}:${env.VERSION}",

                        build:
                        env.BUILD_NUMBER,

                        env:
                        params.TARGET_ENV,

                        type:
                        "BUILD"
                    ])
                }
            }
        }

        stage('Notify Ready') {

            when {
                expression {
                    hasAction('build')
                }                
            }

            steps {

                notify(                    

                    app: params.APP_NAME,

                    env: params.TARGET_ENV,

                    msg: "ARTIFACT READY",

                    version: env.VERSION,

                    commit: params.COMMIT_FULL,

                    md5: env.WAR_MD5,

                    image:
                    "${env.IMAGE}:${env.VERSION}"
                )
            }
        }
    }

    post {

        success {

            echo """
            =====================================
            ✅ BUILD SUCCESS
            =====================================
            """
        }

        failure {

            script {

                notify(

                    app: params.APP_NAME,

                    env: params.TARGET_ENV,

                    msg: "BUILD FAILED ❌",

                    version: env.VERSION,

                    commit: params.COMMIT_FULL,

                    image:
                    "${env.IMAGE}:${env.VERSION}"
                )
            }
        }

        always {

            cleanWs()
        }
    }
}
